name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t test .
      - name: Run image
        run: docker run -d --name netdata test
      - name: Verify
        run: |
          [ $(docker inspect netdata --format='{{.State.Running}}') = 'true' ]
